server:
  port: 8088
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.example.demo_2.entity    # 实体类所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

